# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 16:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsrMgmtModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '9999999999'.", regex=b'^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(blank=True, validators=[django.core.validators.RegexValidator(regex=b'^\\d{6}$')]),
        ),
    ]
